version: '3.3'
services:
  inventory_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'inventory_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'daniel'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'danielpass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./my_db:/var/lib/mysql
  inventory_cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./cache:/data
# Names our volume
volumes:
  cache:
    driver: local
  my-db:
